"""add_media_to_messages

Revision ID: 59918f7921fb
Revises: 4310ac406c28
Create Date: 2026-02-03 11:58:16.096903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59918f7921fb'
down_revision: Union[str, None] = '4310ac406c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('media_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_filename')
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
